exports.seed = function (knex) {
  // Deletes ALL existing entries
  return knex("inventory")
    .del()
    .then(function () {
      // Inserts seed entries
      return knex("inventory").insert([
        //Lush Product (5 Total)
        {
          seller_id: 1,
          event_id: 1,
          name: "Soap",
          category: ["Bath & Body", "Skincare"],
          sku: "lush1",
          units: 100,
          total_quantity: 10000,
          price: 20,
          image: "https://i.imgur.com/3nZlzdS.jpg",
          best_before_date: "2021-05-01T16:49:19.278Z",
          descriptions: "Bath Soap not from Lush",
        },
        {
          seller_id: 1,
          event_id: 1,
          name: "Body Scrub",
          category: ["Bath & Body", "Skincare"],
          sku: "lush2",
          units: 100,
          total_quantity: 2000,
          price: 30,
          image: "https://i.imgur.com/3nZlzdS.jpg",
          best_before_date: "2021-05-02T16:49:19.278Z",
          descriptions: "Body Scrub not from Lush",
        },
        {
          seller_id: 1,
          event_id: null,
          name: "Shampoo",
          category: ["Bath & Body", "Hair Care"],
          sku: "lush3",
          units: 100,
          total_quantity: 5000,
          price: 20,
          image: "https://i.imgur.com/3nZlzdS.jpg",
          best_before_date: "2021-05-01T16:49:19.278Z",
          descriptions: "Shampoo not from Lush",
        },
        {
          seller_id: 1,
          event_id: 1,
          name: "Tinted Lip Balm",
          category: ["Makeup", "Skincare"],
          sku: "lush4",
          units: 100,
          total_quantity: 2000,
          price: 20,
          image: "https://i.imgur.com/3nZlzdS.jpg",
          best_before_date: "2021-05-01T16:49:19.278Z",
          descriptions: "Tinted Lipbalm not from Lush",
        },
        {
          seller_id: 1,
          event_id: null,
          name: "SomethingLush",
          category: ["Bath & Body", "Skincare"],
          sku: "lush5",
          units: 100,
          total_quantity: 20000,
          price: 20,
          image: "https://i.imgur.com/3nZlzdS.jpg",
          best_before_date: "2021-05-01T16:49:19.278Z",
          descriptions: "Another crazy fragrant product not from Lush",
        },
        //Pringles Product (5 total)
        {
          seller_id: 2,
          event_id: null,
          name: "Sweet & Source Pork",
          category: ["Snacks", "Asian", "Western"],
          sku: "Pringles1",
          units: 100,
          total_quantity: 20000,
          price: 21,
          image: "https://i.imgur.com/3nZlzdS.jpg",
          best_before_date: "2021-09-01T16:49:19.278Z",
          descriptions: "Asian flavour",
        },
        {
          seller_id: 2,
          event_id: null,
          name: "Kimchi Beef",
          category: ["Snacks", "Asian", "Western"],
          sku: "Pringles2",
          units: 100,
          total_quantity: 20000,
          price: 23,
          image: "https://i.imgur.com/3nZlzdS.jpg",
          best_before_date: "2021-07-01T16:49:19.278Z",
          descriptions: "Another Asian flavour",
        },
        {
          seller_id: 2,
          event_id: null,
          name: "BBQ Ribs",
          category: ["Snacks", "Western"],
          sku: "Pringles3",
          units: 100,
          total_quantity: 20000,
          price: 22,
          image: "https://i.imgur.com/3nZlzdS.jpg",
          best_before_date: "2021-06-01T16:49:19.278Z",
          descriptions: "Western flavour",
        },
        {
          seller_id: 2,
          event_id: null,
          name: "Sour Cream",
          category: ["Snacks", "Western"],
          sku: "Pringles4",
          units: 100,
          total_quantity: 20000,
          price: 25,
          image: "https://i.imgur.com/3nZlzdS.jpg",
          best_before_date: "2022-05-01T16:49:19.278Z",
          descriptions: "A Classic",
        },
        {
          seller_id: 2,
          event_id: null,
          name: "Jalapeno",
          category: ["Snacks", "Western"],
          sku: "Pringles5",
          units: 100,
          total_quantity: 20000,
          price: 31,
          image: "https://i.imgur.com/3nZlzdS.jpg",
          best_before_date: "2021-04-01T16:49:19.278Z",
          descriptions: "Spicy flavour",
        },
        //Always Products
        {
          seller_id: 3,
          event_id: null,
          name: "Tampon A",
          category: ["Feminine Care"],
          sku: "Always1",
          units: 100,
          total_quantity: 20000,
          price: 20,
          image: "https://i.imgur.com/3nZlzdS.jpg",
          best_before_date: "2021-05-01T16:49:19.278Z",
          descriptions: "Tampon A",
        },
        {
          seller_id: 3,
          event_id: null,
          name: "Tampon B",
          category: ["Feminine Care"],
          sku: "Always2",
          units: 100,
          total_quantity: 20000,
          price: 20,
          image: "https://i.imgur.com/3nZlzdS.jpg",
          best_before_date: "2021-05-01T16:49:19.278Z",
          descriptions: "Tampon B",
        },
        {
          seller_id: 3,
          event_id: null,
          name: "Tampon C",
          category: ["Feminine Care"],
          sku: "Always3",
          units: 100,
          total_quantity: 20000,
          price: 20,
          image: "https://i.imgur.com/3nZlzdS.jpg",
          best_before_date: "2021-05-01T16:49:19.278Z",
          descriptions: "Tampon C",
        },
        {
          seller_id: 3,
          event_id: null,
          name: "Tampon D",
          category: ["Feminine Care"],
          sku: "Always4",
          units: 100,
          total_quantity: 20000,
          price: 20,
          image: "https://i.imgur.com/3nZlzdS.jpg",
          best_before_date: "2021-05-01T16:49:19.278Z",
          descriptions: "Tampon D",
        },
        {
          seller_id: 3,
          event_id: null,
          name: "Tampon E",
          category: ["Feminine Care"],
          sku: "Always5",
          units: 100,
          total_quantity: 20000,
          price: 20,
          image: "https://i.imgur.com/3nZlzdS.jpg",
          best_before_date: "2021-05-01T16:49:19.278Z",
          descriptions: "Tampon E",
        },
        //Pocari Products (5)
        {
          seller_id: 4,
          event_id: null,
          name: "notPocari Sweat",
          category: ["Ready-To-Drink Beverages", "Asian"],
          sku: "Pocari1",
          units: 100,
          total_quantity: 20000,
          price: 20,
          image: "https://i.imgur.com/3nZlzdS.jpg",
          best_before_date: "2021-05-01T16:49:19.278Z",
          descriptions: "Classic",
        },
        {
          seller_id: 4,
          event_id: null,
          name: "notPocari Sweet",
          category: ["Ready-To-Drink Beverages", "Asian"],
          sku: "Pocari2",
          units: 100,
          total_quantity: 20000,
          price: 20,
          image: "https://i.imgur.com/3nZlzdS.jpg",
          best_before_date: "2021-05-01T16:49:19.278Z",
          descriptions: "Classic 2",
        },
        {
          seller_id: 4,
          event_id: null,
          name: "notPocari Swoot",
          category: ["Ready-To-Drink Beverages", "Asian"],
          sku: "Pocari3",
          units: 100,
          total_quantity: 20000,
          price: 20,
          image: "https://i.imgur.com/3nZlzdS.jpg",
          best_before_date: "2021-05-01T16:49:19.278Z",
          descriptions: "Classic 3",
        },
        {
          seller_id: 4,
          event_id: null,
          name: "notPocari Swuut",
          category: ["Ready-To-Drink Beverages", "Asian"],
          sku: "Pocari4",
          units: 100,
          total_quantity: 20000,
          price: 20,
          image: "https://i.imgur.com/3nZlzdS.jpg",
          best_before_date: "2021-05-01T16:49:19.278Z",
          descriptions: "Classic 4",
        },
        {
          seller_id: 4,
          event_id: null,
          name: "notPocari Swaat",
          category: ["Ready-To-Drink Beverages", "Asian"],
          sku: "Pocari5",
          units: 100,
          total_quantity: 20000,
          price: 20,
          image: "https://i.imgur.com/3nZlzdS.jpg",
          best_before_date: "2021-05-01T16:49:19.278Z",
          descriptions: "Classic 5",
        },
        //Kelloggs (5)
        {
          seller_id: 5,
          event_id: null,
          name: "notFrosties",
          category: ["Cereal", "Packaged Meals", "Western"],
          sku: "Kelloggs1",
          units: 100,
          total_quantity: 20000,
          price: 20,
          image: "https://i.imgur.com/3nZlzdS.jpg",
          best_before_date: "2021-05-01T16:49:19.278Z",
          descriptions: "Classic 1",
        },
        {
          seller_id: 5,
          event_id: null,
          name: "notCocoaPuffs",
          category: ["Cereal", "Packaged Meals", "Western"],
          sku: "Kelloggs2",
          units: 100,
          total_quantity: 20000,
          price: 20,
          image: "https://i.imgur.com/3nZlzdS.jpg",
          best_before_date: "2021-05-01T16:49:19.278Z",
          descriptions: "Classic 2",
        },
        {
          seller_id: 5,
          event_id: null,
          name: "notFruitLoops",
          category: ["Cereal", "Packaged Meals", "Western"],
          sku: "Kelloggs3",
          units: 100,
          total_quantity: 20000,
          price: 20,
          image: "https://i.imgur.com/3nZlzdS.jpg",
          best_before_date: "2021-05-01T16:49:19.278Z",
          descriptions: "Classic 3",
        },
        {
          seller_id: 5,
          event_id: null,
          name: "notQuaker Oats",
          category: ["Cereal", "Packaged Meals", "Western"],
          sku: "Kelloggs4",
          units: 100,
          total_quantity: 20000,
          price: 20,
          image: "https://i.imgur.com/3nZlzdS.jpg",
          best_before_date: "2021-05-01T16:49:19.278Z",
          descriptions: "Classic 4",
        },
        {
          seller_id: 5,
          event_id: null,
          name: "notWeetabix",
          category: ["Cereal", "Packaged Meals", "Western"],
          sku: "Kelloggs5",
          units: 100,
          total_quantity: 20000,
          price: 20,
          image: "https://i.imgur.com/3nZlzdS.jpg",
          best_before_date: "2021-05-01T16:49:19.278Z",
          descriptions: "Classic 5",
        },
      ]);
    });
};
